INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();
INSERT INTO Deporte VALUES();

INSERT INTO Marca VALUES();
INSERT INTO Marca VALUES();
INSERT INTO Marca VALUES();
INSERT INTO Marca VALUES();
INSERT INTO Marca VALUES();

INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();
INSERT INTO Pais VALUES();

INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();
INSERT INTO Participante VALUES();

INSERT INTO Imagen VALUES();